use sqlx::{PgPool, Transaction};

use crate::{
    application::{
        repository::{
            RepositoryResult, auth::credential, user,
        },
        security::argon,
    },
    domain::user::{
        User, types::{Email, Password, Username},
    },
};

/// Append one `audit_logs` row.
///
/// Takes the caller's transaction so the audit entry and the `users` mutation
/// it describes commit together or not at all. An admin action that succeeds
/// but leaves no trace, or a trace for an action that rolled back, is worse
/// than no audit trail at all.
///
/// `id` is passed in because `audit_logs.id` is `BIGINT NOT NULL PRIMARY KEY`
/// with no `DEFAULT` and no sequence. The service generates it from the
/// snowflake generator, like every other id in this schema.
///
/// `action_data` is stored as JSONB, so the payload shape is defined by the
/// caller. Keep it to the fields that justify the action (`previous_value`,
/// `new_value`) rather than snapshotting the whole user.
pub async fn write(
    tx: &mut Transaction<'_, sqlx::Postgres>,
    id: i64,
    target_id: i64,
    target_type: &str,
    action: &str,
    performed_by: i64,
    action_data: serde_json::Value,
) -> RepositoryResult<()> {
    sqlx::query(
        r#"
        INSERT INTO audit_logs (
            id,
            target_id,
            target_type,
            action,
            performed_by,
            action_data
        )
        VALUES ($1, $2, $3, $4, $5, $6)
        "#
    )
    .bind(id)
    .bind(target_id)
    .bind(target_type)
    .bind(action)
    .bind(performed_by)
    .bind(action_data)
    .execute(tx.as_mut())
    .await?;

    Ok(())
}

/// What one run of the startup bootstrap decided, for the caller to log.
#[derive(Debug)]
pub enum BootstrapOutcome {
    /// A superuser already exists; nothing was touched.
    Noop,
    /// The `BOOTSTRAP_ADMIN` account existed and was promoted.
    Promoted,
    /// The account did not exist and was created as a superuser.
    Created,
    /// The bootstrap could not ensure a superuser. The message says why.
    Failed(String),
}

/// Ensure a superuser named `username` exists, creating the account if needed.
///
/// Its three branches mirror the three states of a fresh database:
///
/// * **Superuser already exists** — no-op, so a deliberately demoted account is
///   never resurrected and re-running the stack is harmless.
/// * **Username taken** — promote the existing account.
/// * **Username free** — *create* the account (user row, credential, profile)
///   as a superuser. This is the one-boot flow: with `BOOTSTRAP_ADMIN_PASSWORD`
///   set there is no need to register first and restart to get an admin.
///
/// `password` is required only for the create branch — without it there is
/// nothing to hash into `user_credentials` and the account could never log in.
/// `email` is used only there too; it feeds `users.email`, which is unique. The
/// caller (the config) supplies a sane default and lets an operator override it.
/// `user_id` is the snowflake id to seed the new row with, generated by the
/// caller so this stays free of the snowflake generator.
///
/// Runs inside one transaction, so a half-created account can never be left
/// behind. Failures are reported through `Failed` rather than propagated: at
/// boot the only thing lost to an error is the panel, and the caller logs loudly.
pub async fn bootstrap_create(
    pool: &PgPool,
    username: &str,
    password: Option<&str>,
    email: &str,
    user_id: i64,
) -> BootstrapOutcome {
    bootstrap_ensure_admin(pool, username, password, email, user_id)
        .await
        .unwrap_or_else(BootstrapOutcome::Failed)
}

async fn bootstrap_ensure_admin(
    pool: &PgPool,
    username: &str,
    password: Option<&str>,
    email: &str,
    user_id: i64,
) -> Result<BootstrapOutcome, String> {
    let mut tx = pool.begin().await.map_err(|e| e.to_string())?;

    let has_superuser: bool = sqlx::query_scalar(
        r#"
        SELECT EXISTS (SELECT 1 FROM users WHERE is_superuser = true)
        "#,
    )
    .fetch_one(tx.as_mut())
    .await
    .map_err(|e| e.to_string())?;

    if has_superuser {
        return Ok(BootstrapOutcome::Noop);
    }

    let username_taken: bool = sqlx::query_scalar(
        r#"
        SELECT EXISTS (SELECT 1 FROM users WHERE username = $1)
        "#,
    )
    .bind(username)
    .fetch_one(tx.as_mut())
    .await
    .map_err(|e| e.to_string())?;

    if username_taken {
        sqlx::query(
            r#"
            UPDATE users SET is_superuser = true, updated_at = now()
            WHERE username = $1
            "#,
        )
        .bind(username)
        .execute(tx.as_mut())
        .await
        .map_err(|e| e.to_string())?;

        tx.commit().await.map_err(|e| e.to_string())?;
        return Ok(BootstrapOutcome::Promoted);
    }

    let Some(password) = password else {
        return Err(
            "BOOTSTRAP_ADMIN_PASSWORD is required when the admin account does not exist"
                .to_string(),
        );
    };

    let username = Username::new(username)
        .map_err(|e| format!("invalid BOOTSTRAP_ADMIN username: {e}"))?;
    let email = Email::new(email).map_err(|e| format!("invalid bootstrap admin email: {e}"))?;

    let email_taken: bool = sqlx::query_scalar(
        r#"
        SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)
        "#,
    )
    .bind(email.as_str())
    .fetch_one(tx.as_mut())
    .await
    .map_err(|e| e.to_string())?;

    if email_taken {
        return Err(format!(
            "bootstrap admin email '{}' is already registered to another account",
            email.as_str()
        ));
    }

    let password = Password::new(password)
        .map_err(|e| format!("invalid BOOTSTRAP_ADMIN_PASSWORD: {e}"))?;
    let password_hash = argon::hash(password.as_str().as_bytes())
        .map_err(|e| format!("failed to hash BOOTSTRAP_ADMIN_PASSWORD: {e}"))?;

    let account = User {
        id: user_id,
        email,
        username: Some(username),
    };

    user::create::user(&mut tx, &account)
        .await
        .map_err(|e| format!("failed to create bootstrap admin: {e}"))?;

    // `user::create::user` writes the row without touching the role, which is
    // the same leak-proof default every registration relies on; the role is
    // promoted here, inside the same transaction.
    sqlx::query(
        r#"
        UPDATE users SET is_superuser = true, updated_at = now()
        WHERE id = $1
        "#,
    )
    .bind(user_id)
    .execute(tx.as_mut())
    .await
    .map_err(|e| e.to_string())?;

    credential::create_credential(&mut tx, user_id, &password_hash)
        .await
        .map_err(|e| format!("failed to write bootstrap admin credential: {e}"))?;

    user::create::user_profile(&mut tx, user_id, None, None)
        .await
        .map_err(|e| format!("failed to write bootstrap admin profile: {e}"))?;

    tx.commit().await.map_err(|e| e.to_string())?;

    Ok(BootstrapOutcome::Created)
}