pub mod auth_routes;
pub mod user_routes;
pub mod post_routes;
pub mod dev_routes;
pub mod protected_routes;
pub mod message_routes;
pub mod admin_routes;
pub mod guild_routes;
pub mod staff_role_routes;
